### ISSUE TITLE
Unable to connect to Adafruit QTPY ESP32-C3

### ISSUE THREAD

**Issue by brentru** [adafruit/Adafruit_WebSerial_ESPTool#24]
The Adafruit QTPY ESP32-C3 enumerates on the WebSerial ESPTool:
![image](https://user-images.githubusercontent.com/322428/158242189-70a1a401-5b68-40ae-8a13-d882dbf99a20.png)

However, it does not connect, the output log is as follows...
```
Adafruit WebSerial ESPTool loaded.
Connecting...
Connected successfully.
Try to reset.
Performing sync...
Error: Couldn't sync to ESP. Try resetting.
```

Related PR, https://github.com/adafruit/Adafruit_WebSerial_ESPTool/pull/22

**Comment by makermelissa** [comment]
I'll have to wait until I can get my hands on one.

**Comment by makermelissa** [comment]
Ok, just ordered a QTPY ESP32-C3 this morning.

**Comment by makermelissa** [comment]
I figured out why it worked for me. I had put it in bootloader mode by holding boot0 and pressing reset. It didn't just work otherwise. We're going to be referring people to https://nabucasa.github.io/esp-web-flasher/ and I just tested on there and it works fine (after putting in bootloader mode).

**Comment by cantresist** [comment]
> I figured out why it worked for me. I had put it in bootloader mode by holding boot0 and pressing reset. It didn't just work otherwise. We're going to be referring people to https://nabucasa.github.io/esp-web-flasher/ and I just tested on there and it works fine (after putting in bootloader mode).

THANK YOU SO MUCHH
