### ISSUE TITLE
Mac Addresses for ESP32-S2 and ESP32-S3 show up as 00:00:00:00:00:00

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_WebSerial_ESPTool#26]
I must have broken something when restructuring for the C3. This doesn't stop it from its main function though, but it would be nice to fix this.

**Comment by makermelissa** [comment]
I probably should check ESP32 as well since it is using the same code.

**Comment by Jason2866** [comment]
I dont know what i overlooked in the PR. The changes (for the S3 [here)](https://github.com/NabuCasa/esp-web-flasher/pull/107) are working.

**Comment by makermelissa** [comment]
Thanks

**Comment by makermelissa** [comment]
It wasn't reading the eFuses for whatever reason. I changed that and then the code used for the C3 Mac Address worked for the S2 and S3 as well.
