### ISSUE TITLE
Bus error (core dumped)

### ISSUE THREAD

**Issue by 912097713** [adafruit/Adafruit_WebSerial_ESPTool#283]
When i run the script/develop, i get a Bus error (core dumped) with the version 1.2.0.
It's my environment
![图片](https://github.com/user-attachments/assets/d240824c-a76b-44dd-9b8d-1716b4187caa)
npm install
![图片](https://github.com/user-attachments/assets/fe22e0b4-c6c2-4800-bfdd-950092fc05d5)
script/develop
![图片](https://github.com/user-attachments/assets/a4599668-1a98-42fe-9187-3cbfc30b89d4)

i'm not familiar with this project, so can you help.

**Comment by makermelissa** [comment]
Closing as the tool has been updated to use esptool-js internally.
