### ISSUE TITLE
Is it possible to use url for bin file

### ISSUE THREAD

**Issue by ldijkman** [adafruit/Adafruit_WebSerial_ESPTool#29]
Is it possible to use url for bin file

Trying other tools but not 100% succesful
Maybe because i use fs

Adafruit looks to work ok / nice disk bin file

Next Works for wemos d1 and mini and nodemcu 4mbyte i think

https://ldijkman.github.io/randomnerd_esp32_wifi_manager/ProgramESP/index.html

**Comment by makermelissa** [comment]
Not right now. That's what issue #21 is about.
