### ISSUE TITLE
Fix firmware update of WiFi Coprocessor firmware

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_WebSerial_ESPTool#4]
I'm not sure if the uBlox module on the PyPortal Pynt has the same code as the ESP32. If not, the detection and likely new stub code will need to be added.

**Comment by makermelissa** [comment]
In that case, I don't recall testing updating coprocessor firmware at all, though it should work in theory.

**Comment by makermelissa** [comment]
I just tested it out and it's not working. It appears to connect momentarily, but returns a "Didn't get enough status bytes" error.
```
Adafruit WebSerial ESPTool loaded.
Connecting...
Connected successfully.
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 3000 milliseconds
Error: Didn't get enough status bytes
```

**Comment by ladyada** [comment]
does it work with esptool?

**Comment by makermelissa** [comment]
I've previously used ESPTool successfully in the past, but not anytime recently. Also, I tried with the WebSerial version using a regular PyPortal and had the same result.

**Comment by makermelissa** [comment]
Ok, I figured out it was failing when changing baud rates. Setting it to 115200 fixes the issue. I was able to successfully program mine. I think I should add a message when it's changing baud rates so it's easier to troubleshoot in the future.
