### ISSUE TITLE
Fix changing baudrate

### ISSUE THREAD

**Issue by silbo** [adafruit/Adafruit_WebSerial_ESPTool#8]
Thanks for the great efforts put into this project. Great to finally see Web Serial support so this is possible 👍 

### Hardware: 
- ESP WROOM 32
- CH3400 Serial IC
- Macbook Late 2013

### Software:
- Version 89.0.4389.114 (Official Build) (x86_64)
- macOS Big Sur 11.2.3

### Output:
Adafruit WebSerial ESPTool loaded.
Connecting...
Connected successfully.
Try to reset.
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Timed out after 100 milliseconds
Attempting to change baud rate to 460800...
Timed out after 3000 milliseconds
Error: Didn't get enough status bytes

**Comment by makermelissa** [comment]
Try using 115200 if you're seeing this message.

**Comment by silbo** [comment]
Yes the 115200 is the only one that works for me. Wondering if this is a limit currently with the WebSerial or we could improve the code here ?

**Comment by makermelissa** [comment]
I think the code could be improved by adding a try block and falling back to 115200 if it errors and then retrying. I'm going to leave this open for now.

**Comment by conradopoole** [comment]
Just created this PR on NabuCasa's fork to get the baud rate to work above 115200

https://github.com/NabuCasa/ESP-Web-flasher/pull/13
